const fs = require('fs'), p = require('path'), D = p.join(__dirname, '..', 'src', 'data', 'cars');
function a(f, c) {
    let t = fs.readFileSync(p.join(D, f), 'utf-8');
    if (t.includes('"' + c.slug + '"')) { console.log('SKIP ' + c.slug); return; }
    const i = t.lastIndexOf('];');
    t = t.slice(0, i) + ',\n    ' + JSON.stringify(c, null, 8).replace(/\n/g, '\n    ') + '\n' + t.slice(i);
    fs.writeFileSync(p.join(D, f), t, 'utf-8');
    console.log('OK ' + c.slug);
}

// === TOYOTA (3) ===

a('toyota.ts', { id: "toyota-corolla-e100-1-6", slug: "toyota-corolla-e100-1-6-xei", brand: "Toyota", model: "Corolla", variant: "E100 1.6 XEi", years: "1991-1997", generation: "E100", price: 100000, expertNote: "4A-FE 1.6 105 HP. E100 Corolla dünya çapında efsane. Toyota güvenilirliğinin simgesi. Motor ölmez, gövde çürümez. 30 yıllık araçlar hâlâ sorunsuz çalışır.", reliabilityScore: 85, totalIssues: 4, searchCount: 16000, issues: [{ id: "e100-1", title: "Kaporta Pası", description: "30 yıllık araçta bile minimal pas. Ama kontrol şart.", category: "govde", riskLevel: "LOW", affectedKm: "Yaş kaynaklı", repairCost: "Boya" }, { id: "e100-2", title: "Distribütör", description: "Distribütör kapağı ve rotoru aşınması.", category: "motor", riskLevel: "LOW", affectedKm: "80.000+ km", repairCost: "300 - 800 TL" }, { id: "e100-3", title: "Amortisörler", description: "Orijinal amortisörlerin bitik olması.", category: "suspansiyon", riskLevel: "LOW", affectedKm: "Yaş kaynaklı", repairCost: "1.000 - 2.000 TL" }, { id: "e100-4", title: "Cam Fitili", description: "Kapı ve cam fitillerinin sertleşmesi.", category: "govde", riskLevel: "LOW", affectedKm: "Yaş kaynaklı", repairCost: "300 - 800 TL" }], pros: ["Toyota güvenilirliği", "4A-FE ölmez motor", "Pas tutmaz", "Bakım ucuz"], cons: ["Çok eski", "Güvenlik düşük", "Konfor az", "Yavaş"], buyingTips: ["Motor sağlamlığı efsane", "Pas kontrolü şart değil ama yapın", "XEi donanım en iyisi", "Koleksiyoner değeri arttı"] });

a('toyota.ts', { id: "toyota-corolla-e110-1-6", slug: "toyota-corolla-e110-1-6-terra", brand: "Toyota", model: "Corolla", variant: "E110 1.6 Terra", years: "1997-2002", generation: "E110", price: 140000, expertNote: "4A-FE/3ZZ-FE 1.6 110 HP. E110 Corolla daha modern ama aynı güvenilirlik. Terra donanım iyi. Sedan çok yaygın, HB nadir. Toyota kalitesi devam ediyor.", reliabilityScore: 83, totalIssues: 5, searchCount: 14000, issues: [{ id: "e110-1", title: "Yağ Keçesi", description: "Motor yağ keçelerinden hafif sızıntı (yaşa bağlı).", category: "motor", riskLevel: "LOW", affectedKm: "150.000+ km", repairCost: "500 - 1.500 TL" }, { id: "e110-2", title: "Kaporta Pası", description: "Minimal pas ama arka çamurluklar kontrol edilmeli.", category: "govde", riskLevel: "LOW", affectedKm: "Yaş kaynaklı", repairCost: "Boya" }, { id: "e110-3", title: "Ön Süspansiyon", description: "Rotil ve bilyaların aşınması.", category: "suspansiyon", riskLevel: "LOW", affectedKm: "60.000+ km", repairCost: "500 - 1.200 TL" }, { id: "e110-4", title: "Klima Kompresörü", description: "Klima kompresörü arızası (yaşa bağlı).", category: "elektronik", riskLevel: "MEDIUM", affectedKm: "Yaş kaynaklı", repairCost: "2.000 - 4.000 TL" }, { id: "e110-5", title: "Egzoz Sistemi", description: "Egzoz susturucunun çürümesi.", category: "motor", riskLevel: "LOW", affectedKm: "Yaş kaynaklı", repairCost: "500 - 1.500 TL" }], pros: ["Toyota güvenilirliği", "Sağlam motor", "Az arıza", "Değer kaybetmez"], cons: ["Sıkıcı tasarım", "Konfor orta", "Yedek parça pahalılaştı", "Plastik iç mekan"], buyingTips: ["Terra donanım tercih edin", "Motor km'ye bakmayın, bakıma bakın", "Sedan çok yaygın", "Değer kaybı az"] });

a('toyota.ts', { id: "toyota-avensis-t22-1-6", slug: "toyota-avensis-t22-1-6-sol", brand: "Toyota", model: "Avensis", variant: "T22 1.6 Sol", years: "1997-2003", generation: "T22", price: 130000, expertNote: "4A-FE/1ZZ-FE 1.6/1.8. Avensis T22 Toyota'nın Avrupa D segmenti. Corolla güvenilirliğini D segmente taşıdı. Sol donanım zengin. Carina E'nin halefi.", reliabilityScore: 80, totalIssues: 5, searchCount: 10000, issues: [{ id: "t22-1", title: "Yağ Tüketimi (1ZZ)", description: "1ZZ-FE motorlarda yağ tüketimi. Piston segman tasarım sorunu.", category: "motor", riskLevel: "MEDIUM", affectedKm: "100.000+ km", repairCost: "3.000 - 6.000 TL" }, { id: "t22-2", title: "Arka Fren", description: "Arka disk frenlerin aşınması.", category: "fren", riskLevel: "LOW", affectedKm: "40.000+ km", repairCost: "500 - 1.200 TL" }, { id: "t22-3", title: "Kaporta", description: "Minimal paslanma (Toyota kalitesi).", category: "govde", riskLevel: "LOW", affectedKm: "Yaş kaynaklı", repairCost: "Boya" }, { id: "t22-4", title: "Direksiyon Pompası", description: "Hidrolik direksiyon pompası sızıntısı.", category: "suspansiyon", riskLevel: "LOW", affectedKm: "100.000+ km", repairCost: "1.000 - 2.500 TL" }, { id: "t22-5", title: "Gösterge Paneli", description: "Gösterge aydınlatması sönmesi.", category: "elektronik", riskLevel: "LOW", affectedKm: "Yaş kaynaklı", repairCost: "300 - 800 TL" }], pros: ["Toyota güvenilirliği", "D segment konfor", "Az arıza", "Geniş bagaj"], cons: ["Sıkıcı tasarım", "1ZZ yağ tüketiyor", "Yedek parça zor", "Popüler değil"], buyingTips: ["4A-FE motor tercih (1ZZ yağ yer)", "Sol donanım en iyisi", "Sedan ve SW var", "Toyota servisi kullanın"] });

// === HONDA (2) ===

a('honda.ts', { id: "honda-civic-ek-1-6", slug: "honda-civic-ek-1-6-vtec-virs", brand: "Honda", model: "Civic", variant: "EK 1.6 ViRS VTEC", years: "1996-2000", generation: "EK", price: 200000, expertNote: "D16Y 1.6 125 HP VTEC. EK Civic JDM kültürünün sembolü. VTEC devreye girdiğindeki ses efsane. Type R (B16B) koleksiyonluk. Türkiye'de ViRS çok aranır.", reliabilityScore: 82, totalIssues: 5, searchCount: 18000, issues: [{ id: "ek-1", title: "VTEC Solenoid", description: "VTEC solenoid contası sızıntısı. VTEC devreye girmeme.", category: "motor", riskLevel: "MEDIUM", affectedKm: "100.000+ km", repairCost: "500 - 1.500 TL" }, { id: "ek-2", title: "Distribütör", description: "Distribütör arızası. Ateşleme sorunu.", category: "motor", riskLevel: "MEDIUM", affectedKm: "Yaş kaynaklı", repairCost: "500 - 1.500 TL" }, { id: "ek-3", title: "Arka Teker Yatağı", description: "Arka tekerlek rulmanı gürültüsü.", category: "suspansiyon", riskLevel: "LOW", affectedKm: "80.000+ km", repairCost: "500 - 1.000 TL" }, { id: "ek-4", title: "Motor Takozları", description: "Motor takozlarının sertleşmesi.", category: "motor", riskLevel: "LOW", affectedKm: "80.000+ km", repairCost: "500 - 1.200 TL" }, { id: "ek-5", title: "Kaporta Pası", description: "Minimal ama arka çamurluklar kontrol edilmeli.", category: "govde", riskLevel: "LOW", affectedKm: "Yaş kaynaklı", repairCost: "Boya" }], pros: ["VTEC efsanesi", "Honda güvenilirliği", "Sportif sürüş", "JDM kültür ikonu"], cons: ["Fiyatı çok arttı", "Modifiyeli olabilir", "Çalınma riski", "Parça pahalılaştı"], buyingTips: ["Orijinal VTEC mi kontrol edin", "Modifiye geçmişi sorulmalı", "ViRS versiyonu en değerli", "Hırsızlık riski yüksek"] });

a('honda.ts', { id: "honda-accord-cg-2-0", slug: "honda-accord-cg-2-0-es", brand: "Honda", model: "Accord", variant: "CG 2.0 ES", years: "1998-2003", generation: "CG", price: 170000, expertNote: "F20B6 2.0 147 HP. Accord CG büyük, konforlu D segment. Honda güvenilirliği D segmente taşınmış. VTEC motor canlı ve güvenilir. Sedan ve coupe versiyonları.", reliabilityScore: 80, totalIssues: 5, searchCount: 10000, issues: [{ id: "acc-1", title: "Otomatik Şanzıman", description: "Otomatik şanzıman kayması (yüksek km).", category: "sanziman", riskLevel: "HIGH", affectedKm: "200.000+ km", repairCost: "5.000 - 12.000 TL" }, { id: "acc-2", title: "Motor Takozları", description: "Motor takozlarının sertleşmesi. Titreşim.", category: "motor", riskLevel: "LOW", affectedKm: "80.000+ km", repairCost: "1.000 - 2.000 TL" }, { id: "acc-3", title: "Direksiyon Pompası", description: "Hidrolik direksiyon pompası sızıntısı.", category: "suspansiyon", riskLevel: "MEDIUM", affectedKm: "100.000+ km", repairCost: "1.500 - 3.000 TL" }, { id: "acc-4", title: "Klima Kompresörü", description: "Klima kompresörü arızası.", category: "elektronik", riskLevel: "MEDIUM", affectedKm: "Yaş kaynaklı", repairCost: "2.000 - 4.000 TL" }, { id: "acc-5", title: "Kaporta Pası", description: "Minimal paslanma (Honda kalitesi).", category: "govde", riskLevel: "LOW", affectedKm: "Yaş kaynaklı", repairCost: "Boya" }], pros: ["Honda güvenilirliği", "VTEC motor", "D segment konfor", "Az arıza"], cons: ["Otomat riskli", "Yakıt yüksek", "Parça pahalı", "Popüler değil"], buyingTips: ["Manuel şanzıman tercih edin", "F20B motor güvenilir", "ES donanım zengin", "Otomat geçmişi sorulmalı"] });

// === HYUNDAI / KIA (3) ===

a('hyundai.ts', { id: "hyundai-accent-lc-1-5-crdi", slug: "hyundai-accent-lc-1-5-crdi-admire", brand: "Hyundai", model: "Accent", variant: "LC 1.5 CRDi Admire", years: "1999-2005", generation: "LC", price: 110000, expertNote: "D3EA 1.5 CRDi 82 HP. Accent LC Türkiye'de çok satılan ekonomik sedan. CRDi dizel motor güvenilir ve ekonomik. Admire donanım yeterli.", reliabilityScore: 72, totalIssues: 5, searchCount: 14000, issues: [{ id: "alc-1", title: "Turbo Arızası", description: "Turbo yağ kaçağı ve arızası.", category: "motor", riskLevel: "HIGH", affectedKm: "100.000+ km", repairCost: "3.000 - 6.000 TL" }, { id: "alc-2", title: "Enjektör Tıkanması", description: "CRDi enjektörlerin tıkanması.", category: "motor", riskLevel: "MEDIUM", affectedKm: "120.000+ km", repairCost: "3.000 - 8.000 TL" }, { id: "alc-3", title: "Kaporta Pası", description: "Kapı altları ve çamurluk paslanması.", category: "govde", riskLevel: "MEDIUM", affectedKm: "Yaş kaynaklı", repairCost: "Boya / Kaynak" }, { id: "alc-4", title: "Ön Süspansiyon", description: "Ön amortisör ve rotil aşınması.", category: "suspansiyon", riskLevel: "LOW", affectedKm: "40.000+ km", repairCost: "500 - 1.500 TL" }, { id: "alc-5", title: "Elektrik Tesisatı", description: "Elektrik sorunları (cam kaldırma, merkezi kilit).", category: "elektronik", riskLevel: "LOW", affectedKm: "Yaş kaynaklı", repairCost: "500 - 1.500 TL" }], pros: ["Ekonomik dizel", "Ucuz araç", "Basit mekanik", "Yedek parça ucuz"], cons: ["Turbo riski", "Düşük kalite hissi", "Gürültülü", "Güvenlik düşük"], buyingTips: ["CRDi motor ekonomik", "Turbo kontrolü şart", "Admire donanım yeterli", "Ex-ticari mi kontrol edin"] });

a('hyundai.ts', { id: "hyundai-elantra-xd-1-6", slug: "hyundai-elantra-xd-1-6-gl", brand: "Hyundai", model: "Elantra", variant: "XD 1.6 GL", years: "2000-2006", generation: "XD", price: 120000, expertNote: "G4ED 1.6 107 HP. Elantra XD Hyundai'nin C segment sedan aracı. Motor güvenilir, fiyat avantajlı. GL donanım standart. Türkiye'de ticari kullanım çok.", reliabilityScore: 72, totalIssues: 5, searchCount: 10000, issues: [{ id: "exd-1", title: "Motor Conta", description: "Silindir kapağı contası atma riski.", category: "motor", riskLevel: "MEDIUM", affectedKm: "120.000+ km", repairCost: "2.000 - 4.000 TL" }, { id: "exd-2", title: "Otomatik Şanzıman", description: "4 vitesli otomatik şanzıman kayması.", category: "sanziman", riskLevel: "HIGH", affectedKm: "150.000+ km", repairCost: "5.000 - 10.000 TL" }, { id: "exd-3", title: "Kaporta Pası", description: "Paslanma sorunu.", category: "govde", riskLevel: "MEDIUM", affectedKm: "Yaş kaynaklı", repairCost: "Boya / Kaynak" }, { id: "exd-4", title: "Süspansiyon", description: "Ön amortisör ve bilyaların aşınması.", category: "suspansiyon", riskLevel: "LOW", affectedKm: "40.000+ km", repairCost: "500 - 1.500 TL" }, { id: "exd-5", title: "Elektrik", description: "Cam kaldırma ve gösterge arızaları.", category: "elektronik", riskLevel: "LOW", affectedKm: "Yaş kaynaklı", repairCost: "300 - 1.000 TL" }], pros: ["Ucuz araç", "Geniş sedan", "Basit mekanik", "Yedek parça ucuz"], cons: ["Düşük kalite hissi", "Otomat riskli", "Pas sorunu", "Değer kaybı"], buyingTips: ["Manuel şanzıman tercih edin", "Conta geçmişi sorulmalı", "GL donanım yeterli", "Ticari kullanılmış mı kontrol"] });

a('kia.ts', { id: "kia-sephia-1-5-gtx", slug: "kia-sephia-1-5-gtx", brand: "Kia", model: "Sephia", variant: "1.5 GTX", years: "1994-2001", generation: "FA", price: 60000, expertNote: "B5 1.5 80 HP (Mazda 323 tabanlı). Sephia Kia'nın ilk dünya pazarı aracı. Mazda motorlu güvenilir. Türkiye'de çok ucuza satıldı. Yedek parça hâlâ var.", reliabilityScore: 70, totalIssues: 5, searchCount: 6000, issues: [{ id: "sep-1", title: "Motor Conta", description: "Silindir kapağı contası atma riski.", category: "motor", riskLevel: "MEDIUM", affectedKm: "120.000+ km", repairCost: "1.500 - 3.000 TL" }, { id: "sep-2", title: "Kaporta Pası", description: "Ciddi paslanma sorunu.", category: "govde", riskLevel: "HIGH", affectedKm: "Yaş kaynaklı", repairCost: "Boya / Kaynak" }, { id: "sep-3", title: "Şanzıman Senkromece", description: "Manuel şanzıman senkromece aşınması.", category: "sanziman", riskLevel: "MEDIUM", affectedKm: "100.000+ km", repairCost: "2.000 - 4.000 TL" }, { id: "sep-4", title: "Elektrik", description: "Elektrik tesisatı sorunları.", category: "elektronik", riskLevel: "LOW", affectedKm: "Yaş kaynaklı", repairCost: "500 - 1.500 TL" }, { id: "sep-5", title: "Egzoz", description: "Egzoz sistemi çürümesi.", category: "motor", riskLevel: "LOW", affectedKm: "Yaş kaynaklı", repairCost: "500 - 1.500 TL" }], pros: ["Çok ucuz", "Mazda motoru", "Basit mekanik", "Yedek parça var"], cons: ["Pas kabusu", "Düşük kalite", "Güvenlik yok", "Konfor az"], buyingTips: ["Mazda B5 motor güvenilir", "Pas kontrolü ŞART", "GTX donanım en iyisi", "Çok ucuz ama dikkatli olun"] });

// === CİTROEN (3) ===

a('citroen.ts', { id: "citroen-saxo-1-4i", slug: "citroen-saxo-1-4i-sx", brand: "Citroën", model: "Saxo", variant: "1.4i SX", years: "1996-2004", generation: "S0", price: 60000, expertNote: "TU3JP 1.4 75 HP. Saxo Peugeot 106'nın ikizi. Küçük, çevik, ekonomik. VTS versiyonu (120 HP) sportif efsane. Türkiye'de nadir ama aranan araç.", reliabilityScore: 73, totalIssues: 5, searchCount: 6000, issues: [{ id: "sax-1", title: "Debriyaj Teli", description: "Debriyaj telinin kopması.", category: "sanziman", riskLevel: "LOW", affectedKm: "Rastgele", repairCost: "200 - 500 TL" }, { id: "sax-2", title: "Kaporta Pası", description: "Paslanma sorunu.", category: "govde", riskLevel: "MEDIUM", affectedKm: "Yaş kaynaklı", repairCost: "Boya / Kaynak" }, { id: "sax-3", title: "Motor Takozları", description: "Motor takozlarının yorulması.", category: "motor", riskLevel: "LOW", affectedKm: "80.000+ km", repairCost: "500 - 1.000 TL" }, { id: "sax-4", title: "Elektrik", description: "Gösterge ve aydınlatma sorunları.", category: "elektronik", riskLevel: "LOW", affectedKm: "Yaş kaynaklı", repairCost: "300 - 800 TL" }, { id: "sax-5", title: "Egzoz", description: "Egzoz manifoldu çatlağı.", category: "motor", riskLevel: "LOW", affectedKm: "Yaş kaynaklı", repairCost: "500 - 1.200 TL" }], pros: ["Çevik sürüş", "Ekonomik", "VTS sportif", "106 ile ortak parça"], cons: ["Çok küçük", "Nadir araç", "Parça zor", "Konfor yok"], buyingTips: ["VTS varsa koleksiyonluk", "TU3 motor güvenilir", "106 ile parça ortaklığı", "Pas kontrolü"] });

a('citroen.ts', { id: "citroen-xsara-1-6-16v", slug: "citroen-xsara-1-6-16v-sx", brand: "Citroën", model: "Xsara", variant: "1.6 16V SX", years: "1997-2006", generation: "N1", price: 80000, expertNote: "TU5JP4 1.6 16V 110 HP. Xsara WRC şampiyonu Citroen'in yol aracı. İyi sürüş, konforlu. HB, sedan (Berline) ve Break versiyonları. Picasso MPV versiyonu da çok satıldı.", reliabilityScore: 72, totalIssues: 5, searchCount: 10000, issues: [{ id: "xsa-1", title: "Triger Kayışı", description: "Triger kayışı kontrol zamanı.", category: "motor", riskLevel: "CRITICAL", affectedKm: "60.000 km", repairCost: "800 - 1.500 TL" }, { id: "xsa-2", title: "Kaporta Pası", description: "Paslanma sorunu (özellikle arka çamurluklar).", category: "govde", riskLevel: "MEDIUM", affectedKm: "Yaş kaynaklı", repairCost: "Boya / Kaynak" }, { id: "xsa-3", title: "Airbag Sargısı", description: "Direksiyon airbag spiral kablo kopması.", category: "elektronik", riskLevel: "MEDIUM", affectedKm: "Yaş kaynaklı", repairCost: "500 - 1.500 TL" }, { id: "xsa-4", title: "Süspansiyon", description: "Ön süspansiyon bilyaları ve amortisör.", category: "suspansiyon", riskLevel: "LOW", affectedKm: "40.000+ km", repairCost: "500 - 1.500 TL" }, { id: "xsa-5", title: "Cam Kaldırma", description: "Cam kaldırma mekanizması arızası.", category: "govde", riskLevel: "LOW", affectedKm: "Yaş kaynaklı", repairCost: "500 - 1.200 TL" }], pros: ["WRC DNA", "İyi sürüş", "Konforlu C segment", "Ucuz yedek parça"], cons: ["Pas sorunu", "Elektrik arızaları", "Yaşlı", "Parça azalıyor"], buyingTips: ["Triger kontrolü şart", "SX donanım yeterli", "HB daha sportif", "Break pratik"] });

a('citroen.ts', { id: "citroen-c5-mk1-2-0-hdi", slug: "citroen-c5-mk1-2-0-hdi-exclusive", brand: "Citroën", model: "C5", variant: "Mk1 2.0 HDi Exclusive", years: "2001-2008", generation: "DC/DE", price: 120000, expertNote: "DW10 2.0 HDi 109 HP. C5 Mk1 Citroen'in D segment aracı. Hidroaktif süspansiyon (otomatik seviye ayarı). Çok konforlu ama bakım gerektirir.", reliabilityScore: 65, totalIssues: 6, searchCount: 10000, issues: [{ id: "c5-1", title: "Hidroaktif Süspansiyon", description: "Hidroaktif süspansiyon küreleri ve pompa arızası.", category: "suspansiyon", riskLevel: "HIGH", affectedKm: "80.000+ km", repairCost: "5.000 - 12.000 TL" }, { id: "c5-2", title: "DPF Filtresi", description: "DPF filtresinin tıkanması.", category: "motor", riskLevel: "MEDIUM", affectedKm: "Şehir içi", repairCost: "5.000 - 10.000 TL" }, { id: "c5-3", title: "Turbo", description: "Turbo yağ sızıntısı ve arızası.", category: "motor", riskLevel: "HIGH", affectedKm: "120.000+ km", repairCost: "4.000 - 8.000 TL" }, { id: "c5-4", title: "Elektrik", description: "BSI (Body Systems Interface) modülü arızaları.", category: "elektronik", riskLevel: "HIGH", affectedKm: "Yaş kaynaklı", repairCost: "3.000 - 8.000 TL" }, { id: "c5-5", title: "Enjektör", description: "HDi enjektör tıkanması.", category: "motor", riskLevel: "MEDIUM", affectedKm: "120.000+ km", repairCost: "5.000 - 12.000 TL" }, { id: "c5-6", title: "Kaporta Pası", description: "Paslanma sorunu.", category: "govde", riskLevel: "MEDIUM", affectedKm: "Yaş kaynaklı", repairCost: "Boya / Kaynak" }], pros: ["Hidroaktif konfor", "D segment", "Exclusive donanım zengin", "Farklı araç"], cons: ["Süspansiyon ÇOK pahalı", "BSI kabusu", "DPF sorunu", "Bakım maliyetli"], buyingTips: ["Hidroaktif süspansiyon küreleri ne zaman değişti", "BSI arızası kontrol", "DPF temizliği yapılmış mı", "Exclusive donanım güzel ama dikkatli olun"] });

// === DİĞER (2) ===

a('nissan.ts', { id: "nissan-primera-p11-2-0", slug: "nissan-primera-p11-2-0-gx", brand: "Nissan", model: "Primera", variant: "P11 2.0 GX", years: "1996-2002", generation: "P11", price: 80000, expertNote: "SR20DE 2.0 140 HP. Primera P11 Nissan'ın C/D segment aracı. SR20 motor güvenilir ve güçlü. İyi yol tutuşu. Türkiye'de az bilinen ama kaliteli araç.", reliabilityScore: 76, totalIssues: 5, searchCount: 8000, issues: [{ id: "p11-1", title: "Triger Zinciri", description: "SR20 motorlarda triger zinciri gergisi aşınması.", category: "motor", riskLevel: "MEDIUM", affectedKm: "120.000+ km", repairCost: "2.000 - 4.000 TL" }, { id: "p11-2", title: "Motor Takozları", description: "Motor takozlarının sertleşmesi.", category: "motor", riskLevel: "LOW", affectedKm: "80.000+ km", repairCost: "500 - 1.500 TL" }, { id: "p11-3", title: "Kaporta Pası", description: "Minimal paslanma.", category: "govde", riskLevel: "LOW", affectedKm: "Yaş kaynaklı", repairCost: "Boya" }, { id: "p11-4", title: "Egzoz Manifoldu", description: "Egzoz manifoldu çatlağı.", category: "motor", riskLevel: "LOW", affectedKm: "Yaş kaynaklı", repairCost: "500 - 1.500 TL" }, { id: "p11-5", title: "Ön Süspansiyon", description: "Ön amortisör ve bilyalar.", category: "suspansiyon", riskLevel: "LOW", affectedKm: "50.000+ km", repairCost: "500 - 1.500 TL" }], pros: ["SR20 motor güvenilir", "İyi yol tutuşu", "Az bilinen kaliteli araç", "Güçlü 2.0"], cons: ["Yedek parça zor", "Az tanınır", "Değer düşükmüş", "Yaşlı"], buyingTips: ["SR20 motor efsane", "Triger zinciri kontrol", "GX donanım iyi", "Az bilinmesi avantaj (ucuz)"] });

a('seat.ts', { id: "seat-cordoba-1-6-stella", slug: "seat-cordoba-1-6-stella", brand: "Seat", model: "Cordoba", variant: "1.6 Stella", years: "1999-2009", generation: "6K/6L", price: 80000, expertNote: "AKL/BGU 1.6 100 HP. Cordoba VW/Seat platformu. Polo/Ibiza ile ortak parçalar. Ekonomik sedan. Stella donanım Türkiye'ye özel seri.", reliabilityScore: 74, totalIssues: 5, searchCount: 10000, issues: [{ id: "scor-1", title: "Bobinler", description: "Ateşleme bobini arızası.", category: "motor", riskLevel: "MEDIUM", affectedKm: "80.000+ km", repairCost: "500 - 1.500 TL" }, { id: "scor-2", title: "Cam Kaldırma", description: "Cam kaldırma mekanizması arızası.", category: "govde", riskLevel: "LOW", affectedKm: "Yaş kaynaklı", repairCost: "400 - 1.000 TL" }, { id: "scor-3", title: "Kaporta Pası", description: "Kapı altları ve çamurluk pası.", category: "govde", riskLevel: "MEDIUM", affectedKm: "Yaş kaynaklı", repairCost: "Boya / Kaynak" }, { id: "scor-4", title: "Su Pompası", description: "Devridaim pompası sızıntısı.", category: "motor", riskLevel: "MEDIUM", affectedKm: "80.000+ km", repairCost: "500 - 1.500 TL" }, { id: "scor-5", title: "Süspansiyon", description: "Ön süspansiyon burçları aşınması.", category: "suspansiyon", riskLevel: "LOW", affectedKm: "50.000+ km", repairCost: "500 - 1.200 TL" }], pros: ["VW platformu", "Ucuz sedan", "VW/Seat ortak parça", "Ekonomik"], cons: ["Pas sorunu", "Ibiza'dan daha az sportif", "Yaşlanıyor", "Görünüş sade"], buyingTips: ["AKL motor güvenilir", "VW yedek parça kullanılabilir", "Stella donanım yeterli", "Sedan pratik"] });

console.log('\n=== Batch 3 Done (13 cars) ===');
