const fs = require('fs'), p = require('path'), D = p.join(__dirname, '..', 'src', 'data', 'cars');
function a(f, c) {
    let t = fs.readFileSync(p.join(D, f), 'utf-8');
    if (t.includes('"' + c.slug + '"')) { console.log('SKIP ' + c.slug); return; }
    const i = t.lastIndexOf('];');
    t = t.slice(0, i) + ',\n    ' + JSON.stringify(c, null, 8).replace(/\n/g, '\n    ') + '\n' + t.slice(i);
    fs.writeFileSync(p.join(D, f), t, 'utf-8');
    console.log('OK ' + c.slug);
}

// HYUNDAI (4)
a('hyundai.ts', { id: "hyundai-i20-1-4-crdi", slug: "hyundai-i20-mk1-1-4-crdi-style", brand: "Hyundai", model: "i20", variant: "Mk1 1.4 CRDi Style", years: "2009-2014", generation: "PB", price: 280000, expertNote: "U-II 1.4 CRDi 75 HP. i20 Mk1 küçük şehir aracı. Ekonomik dizel. 5 yıl garanti ile satıldı. Style donanım klima, ABS, airbag.", reliabilityScore: 74, totalIssues: 5, searchCount: 10000, issues: [{ id: "i20-1", title: "Turbo", description: "Turbo aktuatör arızası.", category: "motor", riskLevel: "MEDIUM", affectedKm: "100.000+ km", repairCost: "3.000 - 6.000 TL" }, { id: "i20-2", title: "Enjektör", description: "CRDi enjektör tıkanması.", category: "motor", riskLevel: "MEDIUM", affectedKm: "120.000+ km", repairCost: "3.000 - 8.000 TL" }, { id: "i20-3", title: "Direksiyon Pompası", description: "Elektrikli direksiyon arızası.", category: "suspansiyon", riskLevel: "MEDIUM", affectedKm: "80.000+ km", repairCost: "2.000 - 5.000 TL" }, { id: "i20-4", title: "Süspansiyon", description: "Ön amortisör aşınması.", category: "suspansiyon", riskLevel: "LOW", affectedKm: "40.000+ km", repairCost: "500 - 1.500 TL" }, { id: "i20-5", title: "Klima", description: "Klima gazı kaçağı.", category: "elektronik", riskLevel: "LOW", affectedKm: "Yaş kaynaklı", repairCost: "500 - 1.000 TL" }], pros: ["Ekonomik", "5 yıl garanti", "Ucuz bakım", "Şehir aracı"], cons: ["75 HP az", "Küçük araç", "Plastik kalite düşük", "Gürültülü"], buyingTips: ["1.4 CRDi ekonomik", "Style donanım yeterli", "Garanti geçmişi kontrol", "Benzinli 1.4 daha sorunsuz"] });

a('hyundai.ts', { id: "hyundai-i30-1-6-crdi", slug: "hyundai-i30-mk2-1-6-crdi-elite", brand: "Hyundai", model: "i30", variant: "Mk2 1.6 CRDi Elite", years: "2012-2017", generation: "GD", price: 420000, expertNote: "U-II 1.6 CRDi 128 HP. i30 Mk2 Hyundai'nin C segment aracı. İzmit üretimi. Peter Schreyer tasarımı. Elite donanım 7 inç ekran, deri, panoramik tavan.", reliabilityScore: 76, totalIssues: 5, searchCount: 14000, issues: [{ id: "i30-1", title: "DCT Şanzıman", description: "7DCT çift kavrama şanzıman titreşimi.", category: "sanziman", riskLevel: "HIGH", affectedKm: "60.000+ km", repairCost: "8.000 - 18.000 TL" }, { id: "i30-2", title: "Turbo", description: "Turbo aktuatör arızası.", category: "motor", riskLevel: "MEDIUM", affectedKm: "100.000+ km", repairCost: "3.000 - 6.000 TL" }, { id: "i30-3", title: "Enjektör", description: "CRDi enjektör sorunları.", category: "motor", riskLevel: "MEDIUM", affectedKm: "120.000+ km", repairCost: "3.000 - 8.000 TL" }, { id: "i30-4", title: "Süspansiyon", description: "Arka süspansiyon burçları.", category: "suspansiyon", riskLevel: "LOW", affectedKm: "50.000+ km", repairCost: "500 - 1.500 TL" }, { id: "i30-5", title: "Multimedya", description: "Multimedya sistemi donması.", category: "elektronik", riskLevel: "LOW", affectedKm: "Kronik", repairCost: "500 - 2.000 TL" }], pros: ["İzmit üretimi", "C segment", "Elite donanım zengin", "İyi tasarım"], cons: ["DCT şanzıman riskli", "Dizel bakım pahalı", "Değer kaybı", "Plastik kalite"], buyingTips: ["Manuel şanzıman tercih edin", "DCT'den kaçının", "Elite en iyi donanım", "İzmit üretimi kaliteli"] });

a('hyundai.ts', { id: "hyundai-tucson-tl-1-6-crdi", slug: "hyundai-tucson-tl-1-6-crdi-elite", brand: "Hyundai", model: "Tucson", variant: "TL 1.6 CRDi Elite", years: "2015-2020", generation: "TL", price: 800000, expertNote: "D4FE 1.6 CRDi 136 HP. Tucson TL SUV trendinin en popüler araçlarından. Elite donanım 8 inç ekran, CarPlay, şerit takip, kör nokta. Güzel tasarım.", reliabilityScore: 76, totalIssues: 5, searchCount: 16000, issues: [{ id: "tuc-1", title: "DCT Şanzıman", description: "7DCT çift kavrama şanzıman titreşimi.", category: "sanziman", riskLevel: "HIGH", affectedKm: "60.000+ km", repairCost: "8.000 - 18.000 TL" }, { id: "tuc-2", title: "Turbo", description: "Turbo wastegate arızası.", category: "motor", riskLevel: "MEDIUM", affectedKm: "100.000+ km", repairCost: "4.000 - 8.000 TL" }, { id: "tuc-3", title: "EGR", description: "EGR valfi tıkanması.", category: "motor", riskLevel: "MEDIUM", affectedKm: "80.000+ km", repairCost: "2.000 - 5.000 TL" }, { id: "tuc-4", title: "Infotainment", description: "Multimedya donması ve GPS sorunları.", category: "elektronik", riskLevel: "LOW", affectedKm: "Kronik", repairCost: "500 - 2.000 TL" }, { id: "tuc-5", title: "Süspansiyon", description: "Ön amortisör gıcırtısı.", category: "suspansiyon", riskLevel: "LOW", affectedKm: "40.000+ km", repairCost: "1.000 - 2.500 TL" }], pros: ["Güzel tasarım", "Elite donanım süper", "C-SUV", "5 yıl garanti"], cons: ["DCT riskli", "Dizel bakım pahalı", "Fiyatı yüksek", "Yakıt tüketimi"], buyingTips: ["Otomatik yerine manuel alın", "DCT kontrolü", "1.6 CRDi yeterli", "Benzinli 1.6 T-GDi daha sorunsuz"] });

a('hyundai.ts', { id: "hyundai-accent-blue-1-6-crdi", slug: "hyundai-accent-blue-1-6-crdi-mode-plus", brand: "Hyundai", model: "Accent Blue", variant: "1.6 CRDi Mode Plus", years: "2011-2018", generation: "RB", price: 350000, expertNote: "D4FB 1.6 CRDi 128 HP. Accent Blue İzmit üretimi sedan. İç pazar aracı. Mode Plus donanım 7 inç, geri kamera, park sensörü. Ekonomik ve geniş.", reliabilityScore: 74, totalIssues: 5, searchCount: 16000, issues: [{ id: "ab-1", title: "Turbo", description: "Turbo aktuatör arızası.", category: "motor", riskLevel: "MEDIUM", affectedKm: "100.000+ km", repairCost: "3.000 - 6.000 TL" }, { id: "ab-2", title: "Enjektör", description: "CRDi enjektör sorunları.", category: "motor", riskLevel: "MEDIUM", affectedKm: "120.000+ km", repairCost: "3.000 - 8.000 TL" }, { id: "ab-3", title: "DCT", description: "6DCT çift kavrama şanzıman.", category: "sanziman", riskLevel: "HIGH", affectedKm: "60.000+ km", repairCost: "8.000 - 18.000 TL" }, { id: "ab-4", title: "Süspansiyon", description: "Ön amortisör ve bilyalar.", category: "suspansiyon", riskLevel: "LOW", affectedKm: "40.000+ km", repairCost: "500 - 1.500 TL" }, { id: "ab-5", title: "Klima", description: "Klima kompresörü.", category: "elektronik", riskLevel: "MEDIUM", affectedKm: "100.000+ km", repairCost: "2.000 - 4.000 TL" }], pros: ["İzmit üretimi", "Ekonomik", "Geniş sedan", "Ucuz bakım"], cons: ["DCT riskli", "Plastik iç mekan", "Değer kaybı", "Gürültü yalıtımı"], buyingTips: ["Manuel şanzıman tercih", "İzmit üretimi kaliteli", "Mode Plus donanım iyi", "Benzinli 1.4 daha güvenilir"] });

// KIA (3)
a('kia.ts', { id: "kia-ceed-1-6-crdi", slug: "kia-ceed-jd-1-6-crdi-concept-plus", brand: "Kia", model: "Cee'd", variant: "JD 1.6 CRDi Concept Plus", years: "2012-2018", generation: "JD", price: 400000, expertNote: "D4FB 1.6 CRDi 128 HP. Cee'd JD i30'un kardeşi (Hyundai-Kia platformu). İzmit üretimi. Concept Plus donanım zengin. 7 yıl garanti ile ünlü.", reliabilityScore: 76, totalIssues: 5, searchCount: 12000, issues: [{ id: "ced-1", title: "DCT Şanzıman", description: "7DCT çift kavrama titreşimi.", category: "sanziman", riskLevel: "HIGH", affectedKm: "60.000+ km", repairCost: "8.000 - 18.000 TL" }, { id: "ced-2", title: "Turbo", description: "Turbo aktuatör arızası.", category: "motor", riskLevel: "MEDIUM", affectedKm: "100.000+ km", repairCost: "3.000 - 6.000 TL" }, { id: "ced-3", title: "EGR", description: "EGR valfi tıkanması.", category: "motor", riskLevel: "MEDIUM", affectedKm: "80.000+ km", repairCost: "2.000 - 4.000 TL" }, { id: "ced-4", title: "Süspansiyon", description: "Arka burç aşınması.", category: "suspansiyon", riskLevel: "LOW", affectedKm: "50.000+ km", repairCost: "500 - 1.500 TL" }, { id: "ced-5", title: "Multimedya", description: "Multimedya donması.", category: "elektronik", riskLevel: "LOW", affectedKm: "Kronik", repairCost: "500 - 1.500 TL" }], pros: ["7 yıl garanti", "İzmit üretimi", "Concept Plus zengin", "i30 ikizi"], cons: ["DCT riskli", "Dizel bakım pahalı", "Değer kaybı", "Plastik kalite"], buyingTips: ["Manuel tercih edin", "DCT'den kaçının", "7 yıl garanti avantajı", "i30 ile parça ortaklığı"] });

a('kia.ts', { id: "kia-sportage-ql-1-6-crdi", slug: "kia-sportage-ql-1-6-crdi-concept-plus", brand: "Kia", model: "Sportage", variant: "QL 1.6 CRDi Concept Plus", years: "2016-2021", generation: "QL", price: 850000, expertNote: "D4FE 1.6 CRDi 136 HP. Sportage QL Tucson'un kardeşi. Güçlü tasarım, iyi donanım. Concept Plus 8 inç ekran, CarPlay, kör nokta. 7 yıl garanti.", reliabilityScore: 76, totalIssues: 5, searchCount: 14000, issues: [{ id: "spo-1", title: "DCT", description: "7DCT çift kavrama titreşimi.", category: "sanziman", riskLevel: "HIGH", affectedKm: "60.000+ km", repairCost: "8.000 - 18.000 TL" }, { id: "spo-2", title: "Turbo", description: "Turbo wastegate arızası.", category: "motor", riskLevel: "MEDIUM", affectedKm: "100.000+ km", repairCost: "4.000 - 8.000 TL" }, { id: "spo-3", title: "EGR", description: "EGR valfi.", category: "motor", riskLevel: "MEDIUM", affectedKm: "80.000+ km", repairCost: "2.000 - 5.000 TL" }, { id: "spo-4", title: "Süspansiyon", description: "Ön amortisör gıcırtısı.", category: "suspansiyon", riskLevel: "LOW", affectedKm: "40.000+ km", repairCost: "1.000 - 2.500 TL" }, { id: "spo-5", title: "Infotainment", description: "Multimedya donması.", category: "elektronik", riskLevel: "LOW", affectedKm: "Kronik", repairCost: "500 - 2.000 TL" }], pros: ["Güçlü tasarım", "7 yıl garanti", "Concept Plus zengin", "C-SUV"], cons: ["DCT riskli", "Dizel bakım pahalı", "Fiyat yüksek", "Yakıt tüketimi"], buyingTips: ["Manuel veya torque converter otomatik tercih", "DCT'den kaçının", "Tucson'la karşılaştırın", "7 yıl garanti avantaj"] });

a('kia.ts', { id: "kia-rio-1-4-crdi", slug: "kia-rio-ub-1-4-crdi-concept", brand: "Kia", model: "Rio", variant: "UB 1.4 CRDi Concept", years: "2011-2017", generation: "UB", price: 300000, expertNote: "U-II 1.4 CRDi 90 HP. Rio UB küçük şehir aracı. Euro NCAP 5 yıldız. Concept donanım 7 inç ekran, geri kamera. 7 yıl garanti.", reliabilityScore: 75, totalIssues: 5, searchCount: 10000, issues: [{ id: "rio-1", title: "Turbo", description: "Turbo aktuatör.", category: "motor", riskLevel: "MEDIUM", affectedKm: "100.000+ km", repairCost: "3.000 - 6.000 TL" }, { id: "rio-2", title: "Enjektör", description: "CRDi enjektör.", category: "motor", riskLevel: "MEDIUM", affectedKm: "120.000+ km", repairCost: "3.000 - 6.000 TL" }, { id: "rio-3", title: "Süspansiyon", description: "Ön amortisör aşınması.", category: "suspansiyon", riskLevel: "LOW", affectedKm: "40.000+ km", repairCost: "500 - 1.500 TL" }, { id: "rio-4", title: "Klima", description: "Klima gazı kaçağı.", category: "elektronik", riskLevel: "LOW", affectedKm: "Yaş kaynaklı", repairCost: "500 - 1.000 TL" }, { id: "rio-5", title: "Cam Kaldırma", description: "Cam kaldırma mekanizması.", category: "govde", riskLevel: "LOW", affectedKm: "Yaş kaynaklı", repairCost: "400 - 800 TL" }], pros: ["7 yıl garanti", "5 yıldız güvenlik", "Ekonomik", "Ucuz bakım"], cons: ["90 HP yeterli ama az", "Küçük araç", "Plastik kalite", "Gürültülü"], buyingTips: ["Benzinli 1.25 daha sorunsuz", "Concept donanım iyi", "7 yıl garanti avantajı", "İlk araç ideal"] });

// TOYOTA (4)
a('toyota.ts', { id: "toyota-corolla-e150-1-4-d4d", slug: "toyota-corolla-e150-1-4-d4d-elegant", brand: "Toyota", model: "Corolla", variant: "E150 1.4 D-4D Elegant", years: "2007-2013", generation: "E150", price: 350000, expertNote: "1ND-TV 1.4 D-4D 90 HP. E150 Corolla Toyota güvenilirliği devam ediyor. Sakarya Adapazarı üretimi. Elegant donanım deri, klima, CD. Değer kaybı düşük.", reliabilityScore: 80, totalIssues: 5, searchCount: 16000, issues: [{ id: "e150-1", title: "Turbo", description: "Turbo aktuatör arızası.", category: "motor", riskLevel: "MEDIUM", affectedKm: "120.000+ km", repairCost: "3.000 - 6.000 TL" }, { id: "e150-2", title: "DPF", description: "DPF filtresi tıkanması (varsa).", category: "motor", riskLevel: "MEDIUM", affectedKm: "Şehir içi", repairCost: "4.000 - 8.000 TL" }, { id: "e150-3", title: "Süspansiyon", description: "Ön amortisör ve bilyalar.", category: "suspansiyon", riskLevel: "LOW", affectedKm: "50.000+ km", repairCost: "500 - 1.500 TL" }, { id: "e150-4", title: "Enjektör", description: "D-4D enjektör sorunları.", category: "motor", riskLevel: "MEDIUM", affectedKm: "150.000+ km", repairCost: "3.000 - 6.000 TL" }, { id: "e150-5", title: "Klima", description: "Klima kompresörü.", category: "elektronik", riskLevel: "MEDIUM", affectedKm: "100.000+ km", repairCost: "2.000 - 4.000 TL" }], pros: ["Toyota güvenilirliği", "Sakarya üretimi", "Az arıza", "Değer kaybı düşük"], cons: ["90 HP az", "Sıkıcı tasarım", "D-4D parça pahalı", "İç mekan eski"], buyingTips: ["1.33 benzinli daha güvenilir", "Elegant donanım iyi", "Toyota servisi tercih", "Km yüksek olsa da güvenilir"] });

a('toyota.ts', { id: "toyota-corolla-e160-1-4-d4d", slug: "toyota-corolla-e160-1-4-d4d-advance", brand: "Toyota", model: "Corolla", variant: "E160 1.4 D-4D Advance", years: "2013-2019", generation: "E160/E170", price: 550000, expertNote: "1ND-TV 1.4 D-4D 90 HP. E160 Corolla modern tasarım. Sakarya üretimi. Advance donanım 7 inç Touch 2, geri kamera, Toyota Safety Sense.", reliabilityScore: 82, totalIssues: 4, searchCount: 18000, issues: [{ id: "e160-1", title: "Turbo", description: "Turbo aktuatör.", category: "motor", riskLevel: "MEDIUM", affectedKm: "120.000+ km", repairCost: "3.000 - 6.000 TL" }, { id: "e160-2", title: "DPF", description: "DPF tıkanması.", category: "motor", riskLevel: "MEDIUM", affectedKm: "Şehir içi", repairCost: "4.000 - 8.000 TL" }, { id: "e160-3", title: "CVT Şanzıman", description: "CVT titreşimi (CVT varsa).", category: "sanziman", riskLevel: "LOW", affectedKm: "100.000+ km", repairCost: "3.000 - 8.000 TL" }, { id: "e160-4", title: "Süspansiyon", description: "Ön amortisör.", category: "suspansiyon", riskLevel: "LOW", affectedKm: "50.000+ km", repairCost: "500 - 1.500 TL" }], pros: ["Toyota güvenilirliği", "Modern tasarım", "Safety Sense", "Sakarya üretimi"], cons: ["90 HP az", "D-4D parça pahalı", "İç mekan plastik", "CVT tartışmalı"], buyingTips: ["1.33 veya 1.6 benzinli çok daha iyi", "Advance donanım ideal", "Manuel şanzıman tercih", "Toyota'ya özgü düşük değer kaybı"] });

a('toyota.ts', { id: "toyota-yaris-1-33", slug: "toyota-yaris-xp130-1-33-fun", brand: "Toyota", model: "Yaris", variant: "XP130 1.33 Fun", years: "2011-2019", generation: "XP130", price: 350000, expertNote: "1NR-FE 1.33 99 HP. Yaris XP130 küçük ama güvenilir. Toyota kalitesi B segmentte. Fun donanım 6.1 inç ekran, geri kamera. Hybrid versiyonu çok ekonomik.", reliabilityScore: 82, totalIssues: 4, searchCount: 12000, issues: [{ id: "yar-1", title: "CVT Şanzıman", description: "CVT yavaşlama hissi (performans beklentisi).", category: "sanziman", riskLevel: "LOW", affectedKm: "Tasarım", repairCost: "Normal" }, { id: "yar-2", title: "Süspansiyon", description: "Arka amortisör.", category: "suspansiyon", riskLevel: "LOW", affectedKm: "50.000+ km", repairCost: "500 - 1.200 TL" }, { id: "yar-3", title: "Klima", description: "Klima gazı kaçağı.", category: "elektronik", riskLevel: "LOW", affectedKm: "Yaş kaynaklı", repairCost: "500 - 1.000 TL" }, { id: "yar-4", title: "Motor Takozları", description: "Motor takozları sertleşmesi.", category: "motor", riskLevel: "LOW", affectedKm: "80.000+ km", repairCost: "500 - 1.200 TL" }], pros: ["Toyota güvenilirliği", "Az arıza", "Ekonomik", "Hybrid seçeneği"], cons: ["Küçük araç", "99 HP yeterli ama az", "Plastik iç mekan", "CVT sıkıcı"], buyingTips: ["Hybrid varsa kesinlikle tercih edin", "Fun donanım yeterli", "1.33 motor güvenilir", "CVT sorunsuz ama sıkıcı"] });

a('toyota.ts', { id: "toyota-c-hr-1-2-turbo", slug: "toyota-c-hr-1-2-turbo-advance", brand: "Toyota", model: "C-HR", variant: "1.2 Turbo Advance", years: "2016-2023", generation: "AX10", price: 800000, expertNote: "8NR-FTS 1.2 Turbo 116 HP. C-HR Toyota'nın ilk B-SUV/crossover'ı. Çığır açan tasarım. Advance donanım 8 inç, JBL ses, Safety Sense. Hybrid 1.8 çok ekonomik.", reliabilityScore: 80, totalIssues: 4, searchCount: 14000, issues: [{ id: "chr-1", title: "CVT Şanzıman", description: "CVT titreşim hissi.", category: "sanziman", riskLevel: "LOW", affectedKm: "Tasarım", repairCost: "Normal" }, { id: "chr-2", title: "Arka Görüş", description: "Dar arka cam nedeniyle kör nokta fazla.", category: "govde", riskLevel: "LOW", affectedKm: "Tasarım", repairCost: "Normal" }, { id: "chr-3", title: "Süspansiyon", description: "Ön amortisör gıcırtısı.", category: "suspansiyon", riskLevel: "LOW", affectedKm: "40.000+ km", repairCost: "1.000 - 2.000 TL" }, { id: "chr-4", title: "Infotainment", description: "Multimedya donması.", category: "elektronik", riskLevel: "LOW", affectedKm: "Kronik", repairCost: "500 - 1.500 TL" }], pros: ["Çığır açan tasarım", "Toyota güvenilirliği", "Hybrid çok ekonomik", "Safety Sense"], cons: ["Arka koltuk dar", "Görüş alanı kısıtlı", "1.2T yağ tüketimi", "Fiyatı yüksek"], buyingTips: ["Hybrid kesinlikle tercih edin", "1.2 Turbo yağ tüketimi var", "Advance donanım ideal", "Arka koltuk test edin"] });

// HONDA (2)
a('honda.ts', { id: "honda-civic-fc-1-6-vtec", slug: "honda-civic-fc-1-6-i-vtec-eco-elegance", brand: "Honda", model: "Civic", variant: "FC 1.6 i-VTEC Eco Elegance", years: "2016-2021", generation: "FC", price: 800000, expertNote: "R16B 1.6 i-VTEC 125 HP. FC Civic 10. nesil. Çok şık tasarım. Honda Sensing güvenlik paketi. Elegance donanım 7 inç, CarPlay, LED far. T ürkiye'nin en çok satan sedanı oldu.", reliabilityScore: 80, totalIssues: 5, searchCount: 18000, issues: [{ id: "fc-1", title: "CVT Şanzıman", description: "CVT titreşim ve yavaşlama hissi.", category: "sanziman", riskLevel: "LOW", affectedKm: "Tasarım", repairCost: "Normal" }, { id: "fc-2", title: "AC Kompresörü", description: "Klima kompresörü gürültü.", category: "elektronik", riskLevel: "MEDIUM", affectedKm: "80.000+ km", repairCost: "3.000 - 6.000 TL" }, { id: "fc-3", title: "Ön Süspansiyon", description: "Ön amortisör gıcırtısı recall.", category: "suspansiyon", riskLevel: "MEDIUM", affectedKm: "30.000+ km", repairCost: "Recall / 1.500 TL" }, { id: "fc-4", title: "Motor Takozları", description: "Motor takozları titreşim.", category: "motor", riskLevel: "LOW", affectedKm: "60.000+ km", repairCost: "500 - 1.500 TL" }, { id: "fc-5", title: "Infotainment", description: "Honda Connect donması.", category: "elektronik", riskLevel: "LOW", affectedKm: "Kronik", repairCost: "500 - 1.500 TL" }], pros: ["Çok şık tasarım", "Honda güvenilirliği", "Honda Sensing", "1.6 VTEC ekonomik"], cons: ["CVT sıkıcı", "1.6 yavaş hissediyor", "Parça pahalı", "Fiyatı çok arttı"], buyingTips: ["1.0 Turbo daha performanslı", "Elegance donanım ideal", "CVT'ye alışmak lazım", "Honda Sensing hayat kurtarır"] });

a('honda.ts', { id: "honda-hr-v-1-5-vtec", slug: "honda-hr-v-ru-1-5-i-vtec-executive", brand: "Honda", model: "HR-V", variant: "RU 1.5 i-VTEC Executive", years: "2015-2021", generation: "RU", price: 700000, expertNote: "L15B 1.5 i-VTEC 130 HP. HR-V B-SUV segment. Magic Seat sistemi (arka koltuk katlanma). Executive donanım deri, navigasyon, LaneWatch kamera.", reliabilityScore: 80, totalIssues: 4, searchCount: 10000, issues: [{ id: "hrv-1", title: "CVT", description: "CVT titreşim hissi.", category: "sanziman", riskLevel: "LOW", affectedKm: "Tasarım", repairCost: "Normal" }, { id: "hrv-2", title: "AC Kompresörü", description: "Klima kompresörü gürültü.", category: "elektronik", riskLevel: "MEDIUM", affectedKm: "80.000+ km", repairCost: "3.000 - 5.000 TL" }, { id: "hrv-3", title: "Süspansiyon", description: "Ön amortisör gıcırtısı.", category: "suspansiyon", riskLevel: "LOW", affectedKm: "40.000+ km", repairCost: "1.000 - 2.000 TL" }, { id: "hrv-4", title: "Infotainment", description: "Multimedya donması.", category: "elektronik", riskLevel: "LOW", affectedKm: "Kronik", repairCost: "500 - 1.500 TL" }], pros: ["Magic Seat efsane", "Honda güvenilirliği", "B-SUV", "Az arıza"], cons: ["CVT sıkıcı", "130 HP yeterli ama az", "Parça pahalı", "Gürültü yalıtımı"], buyingTips: ["Magic Seat çok pratik", "Executive en iyi donanım", "CVT'ye alışın", "Honda güvenilirliği"] });

console.log('\n=== Ara Kasa Batch 2 Done (13 cars) ===');
